markdown: redcarpet
highlighter: null
permalink: /:title

url: bioinformatics-esalq-usp.github.io
baseurl: /project-name

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
