markdown: redcarpet
highlighter: null
permalink: /:title

url: bioinformatics-esalq-usp.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables, hard_wrap]

sass:
  sass_dir: public/css
  style: :compressed
